---
- name: "Share Certificates"
  when: "utils == 'share-certificates'"
  block:
  - name: "Preflight Checks"
    include_tasks: "share-certificates/00-preflight-checks.yml"
    when: fetch.enabled and utils

  - name: "Fetch certificates from Elasticsearch primary master"
    include_tasks: "share-certificates/01-fetch.yml"
    when: fetch.enabled

  - name: "Copy certificates"
    include_tasks: "share-certificates/02-copy.yml"
    when: copy.enabled

- name: "Convert Logstash server key into pkcs#8"
  when: "utils == 'logstash-key-conversion'"
  block:
  - name: "Preflight Checks"
    include_tasks: "logstash-key-conversion/00-preflight-checks.yml"

  - name: "Convert Key"
    include_tasks: "logstash-key-conversion/01-convert.yml"
